### ISSUE TITLE
Opener Continous Mode - Lock or Button

### ISSUE THREAD

**Issue by Endlessknight** [benzman81/homebridge-nukiio#89] opened 2022-04-26 21:34 UTC
Could you give the option so you can chose if Continous Mode and Ring to Open are exposed in HomeKit either als Switch or Lock?

Example: I have a "leaving home" automation. Whenever I leave my home Continous Mode is turned off and once I returned it gets turned on again.
Due to the fact that Continous Mode ist exposed as a lock and not as a switch I need to manually confirm that I want this automation to run. Which kind of defeats the purpose of the automation if I need to manually turn it off and on just because it's a lock.

I can see the use case for a look too but it would be nice if I can chose if the modes are exposed as lock or switch.

Thanks :)

**Comment by benzman81** [comment] 2022-04-26 22:13
Duplicate of #50

**Closed as completed by benzman81** 2022-04-26 22:13 UTC
Labels: duplicate

**Comment by Endlessknight** [comment] 2022-04-28 06:39
Reopen.

User should have the option to chose for themselves if they want a lock or a switch for the opener modes

**Comment by benzman81** [comment] 2022-04-28 07:28
@Endlessknight Well, this plugin will not support it due to security concerns. 

Anyways, if you like to work around this issue you can use a dummy switch to automate the lock, but I urge you not do this and I am not responsible for any issue that occurs using this workaround. Its your decision.
