### ISSUE TITLE
Homebridge throws exception when running Nuki plugin 

### ISSUE THREAD

**Issue by carbonide** [benzman81/homebridge-nukiio#35] opened 2018-10-24 22:19 UTC
I have Homebridge running on my Synology NAS with several plugins without any problems. But when I try to add the nuki plugin, I get the following error:

`/homebridge/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^
Error: EACCES: permission denied, mkdir '/run/s6/services/homebridge/.node-persist'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/homebridge/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/homebridge/node_modules/mkdirp/index.js:77:24)
    at LocalStorage.parseStorageDirSync (/homebridge/node_modules/node-persist/src/local-storage.js:600:20)
    at LocalStorage.initSync (/homebridge/node_modules/node-persist/src/local-storage.js:141:14)
    at Object.nodePersist.initSync (/homebridge/node_modules/node-persist/src/node-persist.js:37:32)
    at new NukiBridge (/homebridge/node_modules/homebridge-nukiio/nukibridge.js:70:16)
    at new NukiBridgePlatform (/homebridge/node_modules/homebridge-nukiio/index.js:17:23)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:326:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:36)
Disconnected from D-Bus, exiting.
Got SIGTERM, quitting.`

Anybody knows what's going on here?

**Comment by benzman81** [comment] 2018-10-24 22:30
Duplicate of #24 #30 #31

**Closed as completed by benzman81** 2018-10-24 22:30 UTC
