### ISSUE TITLE
Doorlatch setup which locks/switch are shown

### ISSUE THREAD

**Issue by wapster182** [benzman81/homebridge-nukiio#71] opened 2020-12-26 13:01 UTC
Hi,

I have the doorlatch option enabled so I currently have three tiles within the Home App. I show them as seperately. Since I only use the switch and the unlatch withing scenes, I would love to have them not displayed in the same room, only the real lock tile. In Homekit you cannot move them as single tiles, since the are bind together.
Could you implement an option in homebridge, that the locks and switch are natively added as seperate devices, not grouped? Then the user could move them in the rooms independently.

That would be so great!

**Comment by benzman81** [comment] 2020-12-26 14:33
Duplicate of #43.

**Closed as completed by benzman81** 2020-12-26 14:33 UTC
Labels: duplicate
